### PR TITLE
adjust display config

### PR DESCRIPTION
**Pull request by zhiquan-liu**
35808d3 egl/android: config id increase one by one
00ba4e8 egl: correct surface_type when add config
e3767f2 Revert "egl: stop claiming support for pbuffer + msaa"

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@tpalli also for review.

Can you send the patches to Mesa mailing list (Remove Jira ID in your commit :) ) ?

**Comment by tpalli** [comment]
OK, I'll run some testing on these first.

**Comment by tpalli** [comment]
there was regression on following test: piglit.spec.egl 1_4.eglcreatesurface.snbm64 (from piglit), I'll try to reproduce this, not sure why this would happen only with snb

**Comment by zhiquan-liu** [comment]
@tpalli Thanks for testing. I only run deqp, didn't find regression.
After merged here, I will send to Mesa mailing list.

**Comment by kalyankondapally** [comment]
@zhiquan-liu We should really aim for Mesa and not here. Lets please send these to mailing list and see the  feedback.

**Comment by tpalli** [comment]
I tested yesterday on SNB and could not reproduce this failure, maybe something special with the way CI has configured Mesa/Piglit (?) Please send to mesa-dev list and let's see if someone spots anything there. I also re-run on CI and this same test still failed .. weird.

**Comment by zhiquan-liu** [comment]
I have sent them to mesa mailing list.

**Comment by kalyankondapally** [comment]
@zhiquan-liu Whats the status on this, can we close it ?

**Pull request closed without merging**
