### PR TITLE
simd32 enabling forwardported patch series for 1Android 

### PR DESCRIPTION
**Pull request by Shao-Feng**
Patch for optimizing GFXBench KPI (CarChase, Manhattan, Aztec-ruins and T-Rex)

### CODE REVIEW

**Comment by kalyankondapally** [comment]
Can we send these patches to mailing list before merging here.

**Comment by Shao-Feng** [comment]
Hi Kalyan, meet a problem to send all 48 commits to maillist 'mesa-dev@lists.freedesktop.org', via git send-email, 48 mails are generated, and then I am blocked by maillist as a email-robot.

**Comment by Shao-Feng** [comment]
The mail for this patch series is sent, and some feedback is received as below:

**Comment by Shao-Feng** [comment]
this patch series is still under reviewing in upstream. close this one for time being

**Pull request closed without merging**
