### PR TITLE
Fix the path for Shader cache in Android.

### PR DESCRIPTION
**Pull request by Kishore409**
If path not set for cache the default path is taken as '/'
and in Android no permissions to create dir under root.
Below is error message:
Failed to create //.cache for shader cache (Read-only file
system)---disabling.

Change-Id: I485f1b0d7764045e474c57dcb4766e2b1a4f8bb1
Jira: https://jira01.devtools.intel.com/browse/OAM-60964
Test: GPA test acceptance should not throw error.
Signed-off-by: Kishore Kadiyala <kishore.kadiyala@intel.com>

### CODE REVIEW

**Comment by tpalli** [comment]
I would just consider it as a 'message', not error as on Android this is expected behaviour. Problem is that this patch causes driver to actually build up cache in /data/local until the EGL_ANDROID_blob_cache functions are set.

**Comment by js0701** [comment]
Should this to upstream? @Kishore409

**Comment by tpalli** [comment]
@js0701 It's not correct behaviour, disk cache directory creation is supposed to fail on Android.

**Comment by strassek** [comment]
Stale

**Pull request closed without merging**
