### PR TITLE
Don't set swap interval for PBuffer surface.

### PR DESCRIPTION
**Pull request by md-sami**
This fixes crash due to NULL window.
Jira: 61995
Test: CtsDisplayTestCases pass

Signed-off-by: samiuddi <sami.uddin.mohammad@intel.com>

### CODE REVIEW

**Comment by tpalli** [comment]
Yes, makes sense. Please remove the 'Jira' line and send to upstream mesa-dev mailing list.

**Comment by md-sami** [comment]
@tpalli ok sent.

**Comment by kalyankondapally** [comment]
@md-sami I dont think u sent the updated patch to review to mailing list, can u do that ?

**Comment by strassek** [comment]
This patch landed in master. Closing.

**Pull request closed without merging**
