### PR TITLE
FROMLIST: anv/allocator: Loosen the size restriction on imported BOs

### PR DESCRIPTION
**Pull request by strassek**
It's possible for a buffer manager to issue the application a BO that is
larger than what is requested. The out-of-bounds access issue would only
apply in cases where the size of the imported buffer exceeds that of the
underlying BO, as such we should only reject import requests sizes that
exceed the actual size of the BO.

Signed-off-by: Kevin Strasser <kevin.strasser@intel.com>

(am from https://patchwork.freedesktop.org/patch/170066/)
Jira: IAHWC-40
Test: Build IAHWC with Vulkan backend and check that the test apps are
      working on Linux.

### CODE REVIEW

**Comment by tpalli** [comment]
Hmm I think we used to hit this with Vulkan apps but then it went away, why do you have additional padding in the bo? This *should* match the calculations in the driver. It could be that following commit is related:

https://github.com/tpalli/external-vulkan_hal/commit/8aea8eddf82da509d26d740cbb7d0aec79ffa654

**Comment by strassek** [comment]
The extra padding is the result of libdrm issuing the application the first cached buffer it finds that meets or exceeds the requested size:

https://github.com/intel/external-libdrm/blob/master/intel/intel_bufmgr_gem.c#L422

**Comment by kalyankondapally** [comment]
@strassek Can we close this ? I see this has been reviewed already upstream https://patchwork.freedesktop.org/patch/170066/

**Comment by kalyankondapally** [comment]
@tpalli Did we forgot to commit the patch :), I cannot find it merged even though it got reviewed

**Comment by tpalli** [comment]
Yeah, seems like it was forgotten .. I'll check if it still applies cleanly and can push it.

**Comment by tpalli** [comment]
it does not apply to master anymore, there is no size check, either it's been removed or it is somewhere else (?)

**Comment by kalyankondapally** [comment]
@strassek ping

**Comment by kalyankondapally** [comment]
@kevin closing this as discussed

**Pull request closed without merging**
