### PR TITLE
Android: Pass sse4.1 flag as appropriate.

### PR DESCRIPTION
**Pull request by harishkrupo**
We have functions which depend on sse4.1 support but we didnt pass
the right compile flag for it. This patch fixes it.

Signed-off-by: Kalyan Kondapally <kalyan.kondapally@intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@tpalli ping more asking, we should send this to ML ?

**Comment by tpalli** [comment]
It could be that to upstream this we would need version with some detection if SSE4.1 is supported by the platform, in automake case it seems flag is inserted conditionally. This will have impact on texture download/upload paths, please run dEQP just in case to see if something breaks.

**Comment by tpalli** [comment]
doh I was being blind, this is inserted conditionally! I'll merge this and yes, please send to mesa-dev list as is!

**Comment by tpalli** [comment]
Merged in, many thanks!

**Pull request closed without merging**
