### PR TITLE
Heuristic patch for SIMD32 optimization for Automotive customers

### PR DESCRIPTION
**Pull request by downor**
This is a CR for the latest heuristic patch for SIMD32 optimization from KPI team for various IOTG automotive programs. This is to give customers an option (upon their request) to use SIMD32 optimization for the best optimal performance on their 3D applications (like Navigation).

### CODE REVIEW

**Comment by downor** [comment]
@kalyankondapally 
Can this be merged by the end of this week? This blocks code-freeze for MR4 Gold (IOTG APL Yocto)

**Comment by tpalli** [comment]
Is Toni planning to upstream these patches soon?

**Comment by downor** [comment]
@tpalli 
Yes, that is my understanding. However, Toni also mentioned VTT is working on profiling to more optimized result. I am not sure that approach will yield different kinds of patchsets that can replace this series. I think he is not 100% sure these will land in Mesa upstream. But anyway, customer wants to try SIMD32 with the latest heuristic. So I hope this will be approved ASAP (for this branch only is fine.) unless there's any critical concern. Kalyan and I had an agreement that functional validation on this branch will be done and guaranteed by IOTG.

**Comment by downor** [comment]
@kalyankondapally 
Kalyan, Not sure why it gets one pending check above. According to travis-ci report, all tests have passed.
Can you help merge this if there's no further concerns? Thanks

**Pull request merged**
