### PR TITLE
Mesa

### PR DESCRIPTION
**Pull request by kanlihu**
mesa: don't forget to clear _Layer field on texture unit

On the Android Antutu benchmark we ran into an assert in ISL where the
(base layer + num layers) > total layers. It turns out the core of
mesa forgot to clear the _Layer variable, potentially leaving an
inconsistent value.

enable GLX_USE_TLS on android
    
On the Android deqp test when we run
dEQP-EGL.functional.sharing.gles2.multithread.random.textures.gen_delete.15
we will find two thread using one context. It will case gpu hang.

draw 2 prims in GL_PATCH mode.
    
antutu 7.3 benchmark test will cause gpu hang
when I draw 2 prims in one glDrawElements command, The gpu hang won't be reproduced.

### CODE REVIEW

**Comment by tpalli** [comment]
The commit message in the "mesa: don't forget to clear _Layer field on texture unit" patch does not match upstream patch, something has went wrong there.

**Review by feijiang1 — APPROVED** [review]

**Review by feijiang1 — APPROVED** [review]

**Review by feijiang1 — APPROVED** [review]

**Comment by tpalli** [comment]
@feijiang1 Did you spot my comment? The commit message on first patch is invalid, see following lines:

```
Signed-off-by: Lionel Landwerlin's avatarLionel Landwerlin <lionel.g.landwerlin@intel.com>
Reviewed-by: Eric Engestrom's avatarEric Engestrom <eric.engestrom@intel.com>
Reviewed-by: Jason Ekstrand's avatarJason Ekstrand <jason@jlekstrand.net>
```

Please do not copy-paste or handwrite patches. You can use git format-patch or save the patches from gitlab instead.

**Comment by renchenglei** [comment]
So sorry, I also break the rule with my previous PR https://github.com/intel/external-mesa/pull/139.
Recently, we have a urgent integration to celadon. Once it is done, we will consider a new round of mesa rebase from upstream, which the mesa version is 19.3.x now. Then we will scrub all of Android specific patch. Reorganize the commit info(e.g add [INTERNAL] to title; rewrite reviewer :) )

**Comment by feijiang1** [comment]
@tpalli sorry, I didn't notice your comments when merge the patch, we will pay attention for that. As Chenglei's said, we will do a new round of mesa rebase, it will be fixed that time.

**Pull request merged**
