### PR TITLE
Compiler optimizations enabled for mesa

### PR DESCRIPTION
**Pull request by yogesh-marathe**
Improves performance of graphics tests significantly.

Signed-off-by: Yogesh Marathe <yogesh.marathe@intel.com>

### CODE REVIEW

**Comment by tpalli** [comment]
Which benchmarks are affected? TBH I'm not sure if this is safe considering the default is O2 for all distros.

**Comment by tpalli** [comment]
There has been some previous investigation on using O3, this was with gcc though, clang might behave a lot different. In previous investigations it was found out that O3 did not bring much performance improvement itself. When using with 'march' it brings some SSE optimizations that will benefit texture upload, however for typical GL app it did not bring performance benefit. It was found out that in some cases link time optimization (-flto) brings more performance than toggling O3.

If we decide to toggle O3 on, we need to do some careful performance analysis and also compile log analysis that there are no warnings about strict aliasing (that gets turned on when O3 is on), there has been previous Mesa bugs about aliasing and I believe there might be aliasing issues within current Mesa tree.

**Comment by yogesh-marathe** [comment]
Yes its not easy to switch to O3 and needs lot of testing. I saw in release notes couple of bugs pertaining to O3 were fixed around 13.0.x or so, and then I enabled this. I will pull out the reference if I find again but for the benchmarks we run for performance it showed perf improvements without functional issues. As you mentioned I should be checking logs to see warnings too. I was trying -Ofast along with this, will update on that too. Thanks for linker options, but I haven't yet moved to linker. Will try that for sure.  Any specific functionality tests you are looking for enabling O3?

**Comment by yogesh-marathe** [comment]
I tried -Ofast too, there is no noticeable difference performance wise between -O3 and -Ofast.

**Comment by kalyankondapally** [comment]
close this or still something needs to be done here ?

**Comment by tpalli** [comment]
The O3 was added, yeah we can close this one.

**Pull request closed without merging**
