### PR TITLE
Mesa Static link with libexpat

### PR DESCRIPTION
**Pull request by Kishore409**
Mesa Static link with libexpat
In Android O, MESA needs to statically link libexpat
so that it's in same namespace.

Signed-off-by: Kishore Kadiyala <kishore.kadiyala@intel.com>

### CODE REVIEW

**Comment by tpalli** [comment]
Why libexpat, is there particular issue with that?

**Comment by Kishore409** [comment]
After introducing treble, dynamic linking of lib with MESA is not happening.
We had workaround for it as temporary fix . Meanwhile when contacted google, they suggested that , MESA should statically link libexpat.

**Comment by tpalli** [comment]
Right, I'm just wondering how does it work for other libs like libz, liblog (?) I guess it would be good to upstream these changes.

**Comment by kalyankondapally** [comment]
@harishkrupo  will be sending it out for review. While it's ongoing can we get this merged here @tpalli

**Comment by harishkrupo** [comment]
@tpalli @kalyankondapally Sure. I will. Is the commit message enough?
> Right, I'm just wondering how does it work for other libs like libz, liblog (?)

Yeah, how come these two libraries link fine?

**Comment by tpalli** [comment]
When sending upstream it would be good to mention what is failing and how to trigger it. As example with current Android-IA things work fine without this change so one would think there is no problem.

**Comment by kalyankondapally** [comment]
@tpalli Dont think Android IA enables full treble mode yet. On that note, I dont think we can send this upstream yet.

@tpalli @harishkrupo Those might be whitelisted as lot of components use those packages. libexpat is not used by anyone except mesa.

**Comment by tpalli** [comment]
Right I see .. let's use this just internally for now then.

**Comment by kalyankondapally** [comment]
merged

**Comment by Kishore409** [comment]
Will be posting an updated, closing this PR

**Pull request closed without merging**
