### PR TITLE
REVERTME: anv/android: enable/disable couple of KHR extensions for Android CTS

### PR DESCRIPTION
**Pull request by renchenglei**
This patch is similar to c9a5ddb0e88b8be24f523a1ca6fae61637e0ffe5,
VK_KHR_create_renderpass2 is alreadly whitelisted in CTS, so we add
it back, and 3 more new extensions cause CTS fail, we disable them to
pass following two CTS cases.

dEQP-VK.api.info.device.extensions
dEQP-VK.api.info.android#no_unknown_extensions

Signed-off-by: Chenglei Ren <chenglei.ren@intel.com>

### CODE REVIEW

**Comment by renchenglei** [comment]
@tpalli & @strassek , could you help take a review of this changes?

**Comment by tpalli** [comment]
I'd prefer to split this to 2 commits. One is a simple revert and 2nd one takes care of the new extensions. This makes is easier to deal later as your commit will also likely be reverted in future as extensions get enabled.

**Comment by jennycao** [comment]
Chenglei, pls only disable the 2 new extensions which not in CTS whitelist in this PR, 
For the VK_KHR_create_renderpass2 change,  @strassek  or @js0701 can help to revert the  android specific  patch c9a5ddb.

**Comment by renchenglei** [comment]
Thanks all for the comments. 
I updated the PR, which only disable the 3 new extension.
For VK_KHR_create_renderpass2, this has been added to CTS white list:
https://android.googlesource.com/platform/external/deqp/+/df3667a14daeb798db79e617203550f587f954f9%5E%21/#F0
We have two choices:
1. Prepare another PR to enable it in our mesa;
2. @strassek help make the changes in commit c9a5ddb during next round of rebase, as c9a5ddb has disabled two extensions, we need make some changes.

**Comment by tpalli** [comment]
Right, if there's a rebase planned soon then we can simply drop my patch during that rebase. If not, then just include patch in this PR to revert my patch.

**Comment by strassek** [comment]
I can squash this and tpalli's patch together and land in the next rebase.

**Comment by renchenglei** [comment]
It(VK_KHR_create_renderpass2) won't affect the CTS results, maybe we could deal with it during next round rebase. :)
@jennycao is working on one round of mesa rebase to Celadon, once she finish it, maybe we could consider rebase upstream mesa to our github.
@tpalli do you have any idea about which version we should rebase to our github?

**Comment by tpalli** [comment]
@renchenglei There's a release of Mesa 19.0 now, I would propose that. There's a lot of changes and improvements especially on Vulkan side. Mesa 19 also supports VK_ANDROID_external_memory_android_hardware_buffer. I have rebased most (if not all patches) and things seem to be working fine, I haven't done full CTS though so there might be some new issues lurking.

One observed thing is blinking elements in some benchmarks like 3DMark, Basemark ES 3.1 and Basemark GPU but I believe I saw that with older Mesa too and it started around same time we integrated preemption patches.

Having said that, I can spot some issues during CTS that need fixing, so we should plan the rebase to happen in just a phase that we have enough time to fix these.

**Comment by strassek** [comment]
19.0 looks like the right target, I'll start the rebase. We can always roll back to 18.3 if there is some major blocker.

**Comment by strassek** [comment]
I reverted @tpalli's patch, applied this one, and squashed everything together. Merged the result in my 19.0 candidate branch here:
https://github.com/strassek/external-mesa/commit/59bf1e9e74c6d0365e4442a93c398f234175ece0

**Comment by renchenglei** [comment]
Thanks @tpalli  & @strassek !
VK_KHR_8bit_storage extension is still not in white list for CTS 9.0-r6, could we also add it to strassek@59bf1e9?

**Comment by strassek** [comment]
@renchenglei Sure, I can add that back in. In general I'll make sure the above tests actually pass before pushing anything.

**Comment by renchenglei** [comment]
@strassek & @js0701 , if this PR is ok for 18.3.2, could we get this merged. Celadon code is open now, once we get this merged, @jennycao will help rebase 18.3.2 to Celaodn(Thanks Jenny).

**Comment by strassek** [comment]
@renchenglei I'm already well into testing the 19.0 rebase (including these patches), so far it's looking good. The path to pushing 19.0 to master will be shorter than that of an 18.3 rebase. I'm estimating I'll have it wrapped up by tomorrow evening.

**Comment by jennycao** [comment]
@strassek  Pls help to merge this patch, I would push the 18.3.2 to celadon with this patch today.

**Comment by strassek** [comment]
Landed these changes in master as https://github.com/intel/external-mesa/commit/fefad30c05b3fd9e403329bee78e928101a79e53

**Pull request closed without merging**
