### PR TITLE
i965: perf: implement GPA's null renderer

### PR DESCRIPTION
**Pull request by yugang**
GPA requires a null renderer query which disables all rendering. This
feels fairly at odds with the spirit of the INTEL_performance_query
extension.

Test: Pass mdapi test_GfxDrv_DriverAcceptance test case
      GfxDrv_DriverAcceptanceQuery.GL_NULL_HARDWARE and has no reg issue
Signed-off-by: Landwerlin, Lionel <lionel.g.landwerlin@intel.com>

submit https://github.com/djdeath/mesa/commit/ba47f5fdb998d2fb6d0175f940f17070cf63c874 to fix
MDAPI tests GfxDrv_DriverAcceptanceQuery.GL_NULL_HARDWARE in Android

### CODE REVIEW

**Comment by js0701** [comment]
@kalyankondapally

**Comment by strassek** [comment]
@djdeath Do you think there is a path to getting this patch accepted upstream?

**Comment by djdeath** [comment]
I don't think so because this is clearly a introducing a behavior that has nothing to do with performance queries.
We published another extension to implement the same behavior : https://www.khronos.org/registry/OpenGL/extensions/INTEL/INTEL_blackhole_render.txt
Unfortunately the effort kind of stalled : https://patchwork.freedesktop.org/series/40035/

**Comment by strassek** [comment]
Thanks Lionel!

@yugang Can we try to land INTEL_blackhole_render instead?

**Comment by yugang** [comment]
@strassek considering the INTEL_blackhole_render need test case changes and also need time to review in upstream(i tried the INTEL_blackhole_render and met the failure, and confirmed with Lionel that the tests need changes. i think the tests should be changeed once the INTEL_blackhole_render get merge in upstream), but the Android milestone is so urgent, so i suggest we can use this patch firstly, and rebase it once the INTEL_blackhole_render and tests get merged.

**Comment by strassek** [comment]
Understood, in that case lets prepend the commit subject with "REVERTME: ..." and add a note in the body with an explanation and a link to Lionel's series. It could be a long time until someone looks at this again.

**Comment by yugang** [comment]
@strassek , thanks for your comments, and updated the PR already

**Comment by yugang** [comment]
@js0701 @kalyankondapally @jennycao not sure if can merge it for next release?

**Comment by js0701** [comment]
Will merge if no more comments. @yugang

**Comment by strassek** [comment]
I have a rebase + this patch running through dEQP atm, I'll push it to master tomorrow morning.

**Comment by strassek** [comment]
Merged

**Pull request closed without merging**
