### PR TITLE
Backport patches for Prioritized Rendering

### PR DESCRIPTION
**Pull request by gaochun**
Backport mesa patches and solve the conflicts. The patches are from:
https://patchwork.freedesktop.org/patch/149865/
https://patchwork.freedesktop.org/patch/149694/
https://patchwork.freedesktop.org/patch/149693/
https://patchwork.freedesktop.org/patch/149695/

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@tpalli  Fine if we merge these ? One change is missing i.e. Defines declared in the header. I have it locally, tested in and doesn't seem to cause any new issues. We also need to enable support for using this in frameworks/native.

**Comment by tpalli** [comment]
I've been working hard to keep our patch count against master minimal, IMO it's not a great idea to grow that pile :/ But if this helps upstreaming these patches then we should do it.

**Comment by kalyankondapally** [comment]
@tpalli understood and agree with that. These are something we need to get things moving forward while upstream is in process of getting them merged.

**Comment by kalyankondapally** [comment]
merged

**Pull request closed without merging**
