### PR TITLE
REVERTME: glsl: disallow to eliminate first elements of the ub/ssbo array

### PR DESCRIPTION
**Pull request by renchenglei**
This is a draft to fix following CTS issue:
dEQP-GLES31.functional.ssbo.layout.random.all_per_block_buffers#18
This failure is new due to CTS package upgrade from 9.0 r5 to 9.0 r6.
We have validated this pacth on 1A and no regression found. We would
keep this changes same with 1A, and once upstream has final fix, we
would replace this draft with final fix.

Signed-off-by: Andrii Simiklit <andrii.simiklit@globallogic.com>
Change-Id: Ibd32222ddf7f549649cf176aa12722945066e7f1

### CODE REVIEW

**Comment by renchenglei** [comment]
There is one bug to track this issue, https://bugs.freedesktop.org/show_bug.cgi?id=109532
We would keep tracking this issue, and once the final fix land, we would like to change this draft to final fix.

**Comment by strassek** [comment]
LGTM, I'll pull the version from https://gitlab.freedesktop.org/mesa/mesa/merge_requests/332/ in the next rebase.

**Comment by renchenglei** [comment]
Thanks @strassek !

**Comment by strassek** [comment]
I pulled the 2 patches from gitlab into my 19.0 candidate branch here:
https://github.com/strassek/external-mesa/commit/e64a511e41cb5c9871b465c8340d561043d12993
https://github.com/strassek/external-mesa/commit/eda6d6297993e7681ee4cedcc2de1daa9b8279d2

**Comment by renchenglei** [comment]
@strassek & @js0701 , if this PR is ok for 18.3.2, could we get this merged. Celadon code is open now, once we get this merged, @jennycao will help rebase 18.3.2 to Celaodn(Thanks Jenny).

**Comment by jennycao** [comment]
@strassek Pls help to merge this patch, I would push the 18.3.2 to celadon with this patch today.

**Comment by strassek** [comment]
Landed these changes in master as https://github.com/intel/external-mesa/commit/997a975b3976369f06ccafca06c98846ce9abc73 and https://github.com/intel/external-mesa/commit/a92a787d1e0dce0541ef7cdea703de47a34c2599

**Pull request closed without merging**
