### PR TITLE
Disable EXT_pixel_format_float for Android CtsViewTestCases

### PR DESCRIPTION
**Pull request by Kishore409**
Android CTS should PASS for below
  android.view.cts.PixelCopyTest#testWideGamutWindowProducerCopyToRGBA16F

### CODE REVIEW

**Comment by kalyankondapally** [comment]
Dont want revert of reverts, removed the original revert . Sorry :(

**Comment by tpalli** [comment]
FYI, I have a 'in process fix' for the wide color tests, the commit on top of this tree should fix the cases for now:

https://github.com/tpalli/external-mesa/tree/astc_cleanup

**Comment by kalyankondapally** [comment]
@tpalli Does this fix Android CtsViewTestCases ?

**Comment by tpalli** [comment]
unfortunately not, only the dEQP wide color ones

**Pull request closed without merging**
