### PR TITLE
Enabling EGL_KHR_image_pixmap extension

### PR DESCRIPTION
**Pull request by harishkrupo**
As Android does not have the concept of a pixmap, one can use this
extension to create an EGLImage from ANativeWindowBuffer.

Jira: None
Tests: Extension is advertised in the egl extensions string

Signed-off-by: Harish Krupo <harish.krupo.kps@intel.com>

### CODE REVIEW

**Comment by harishkrupo** [comment]
@kalyankondapally @tpalli Could you please review it?

**Comment by tpalli** [comment]
I don't think this extension should be exposed on Android, applications should use EGL_ANDROID_image_native_buffer extension instead?

**Comment by harishkrupo** [comment]
In the file frameworks/native/opengl/libs/EGL/eglApi.cpp line 100, Android exposes this extension to applications via its egl wrapper. What I don't understand is, why expose it when it cannot support native pixmap creation. It is not marked mandatory, though.

**Comment by tpalli** [comment]
Right, there has been also bug about exposing it against Android Gingerbread but it was resolved as wontfix (without explanation). My proposal would be to not expose it unless we encounter something that utilizes it like this because using pixmap extension by feeding it android surface is not defined by the spec.

**Comment by harishkrupo** [comment]
sure :+1:

**Comment by harishkrupo** [comment]
Closing as Android doesn't support pixmaps

**Pull request closed without merging**
