### PR TITLE
i965: reorder the screen configs

### PR DESCRIPTION
**Pull request by txu4**
Move the RGB565 from top to bottom, then dEQP test will pick 32bpp configure first.
It can solve the dEQP failure due to precision issue.
dEQP-GLES3.functional.fragment_ops.blend.default_framebuffer.rgb_func_alpha_func.src

JIRA: https://01.org/jira/browse/AIA-8
Test: No regression and solve one dEQP issue on Android-IA platform

### CODE REVIEW

**Comment by txu4** [comment]
@tpalli  and @kalyankondapally Please review and merge

**Comment by tpalli** [comment]
hmm for me there's still 9 failing tests in this category .. I'll retry, maybe something went wrong.

**Comment by kalyankondapally** [comment]
can u prefix the commit message with AndroidIA:  ?

**Comment by tpalli** [comment]
txu4 can you also re-run tests, for me it looks like end result has changed with this one, even if I remove the whole 565 config, tests are still failing. I also noticed that dEQP has been patches to exclude 565 blend cases (commit named "Exclude RGB565 blending cases from the must-pass")

**Comment by txu4** [comment]
@tpalli Thanks, Mingwei's test result shows this issue is solved.

**Comment by tpalli** [comment]
ok superb!

**Pull request closed without merging**
