### PR TITLE
Add compile guard for Gralloc1

### PR DESCRIPTION
**Pull request by harishkrupo**
Add the ifdef guard for the function get_ycbcr_from_flexlayout
to prevent it from being compiled when using Gralloc0.

Signed-off-by: Harish Krupo <harish.krupo.kps@intel.com>

### CODE REVIEW

**Review by tpalli — APPROVED** [review]
OK, will merge. I'll later squash this together with the patch that added those parts.

**Comment by harishkrupo** [comment]
Sure, Thank you :+1:

**Comment by tpalli** [comment]
hmm one thing though, where is HAVE_GRALLOC1 define coming from?

**Comment by tpalli** [comment]
We already include gralloc1 header in egl_dri2.h so we could check for GRALLOC_MODULE_API_VERSION_1_0 I guess? There seems no HAVE_GRALLOC1 within current Mesa build.

**Comment by harishkrupo** [comment]
Looks like it is missing after the rebase.

**Comment by harishkrupo** [comment]
> We already include gralloc1 header in egl_dri2.h so we could check for GRALLOC_MODULE_API_VERSION_1_0 I guess

The header is available on Android N and above only.

**Comment by tpalli** [comment]
> Looks like it is missing after the rebase.

argh ok so I screwed up with the rebase, will check which patch I missed

> The header is available on Android N and above only.

Yep, the header should be also included conditionally. *Ideally* though we should not have such ifdefs in place at all and had a separate file that abstracts the gralloc interface so that we use same code for both versions.

**Comment by tpalli** [comment]
ah ok now I see, I've merged a different version of the 'defer format detection for gralloc1.0' patch, not sure how I managed to do that, will fix this

**Comment by harishkrupo** [comment]
>  Ideally though we should not have such ifdefs in place at all and had a separate file that abstracts the gralloc interface so that we use same code for both versions. 

Even in this case, we will have to use some ifdef (maybe ANDROID_API_LEVEL) to prevent inclusion of gralloc1 header on versions where it is not present.

**Comment by tpalli** [comment]
> Even in this case, we will have to use some ifdef (maybe ANDROID_API_LEVEL) to prevent
> inclusion of gralloc1 header on versions where it is not present.

sure, but not scattered all over the place like now is

**Comment by tpalli** [comment]
merged

**Pull request closed without merging**
