### PR TITLE
Minor autogen build issue fixed

### PR DESCRIPTION
**Pull request by yogesh-marathe**
This issue is faced in standanlone mesa build

Signed-off-by: Yogesh Marathe <yogesh.marathe@intel.com>

### CODE REVIEW

**Comment by tpalli** [comment]
That's strange, what is the error from build without this change?

**Comment by yogesh-marathe** [comment]
This is the error you get

src/egl/Makefile.am:85: error: libEGL_la_LIBADD must be set with '=' before using '+='

libEGL_la_LIBADD isn't set anywhere else before as I checked.

**Comment by kalyankondapally** [comment]
I am also seeing this with a clean build on Linux 

src/egl/Makefile.am:85: error: libEGL_la_LIBADD must be set with '=' before using '+='
autoreconf: automake failed with exit status: 1

**Comment by tpalli** [comment]
ok now I understand, this is caused by one of the patches we apply on top of Mesa, will apply this to next rebase (tomorrow), thanks!

**Pull request closed without merging**
