### PR TITLE
Mesa: Return GL error INVALID_OPERATION in case invalid format/type

### PR DESCRIPTION
**Pull request by txu4**
Refer to GLES3.2 spec in 8.5
Textures with a base internal format of DEPTH_COMPONENT, DEPTH_-
STENCIL or STENCIL_INDEX are supported by texture image specification
commands only if target is TEXTURE_2D, TEXTURE_2D_MULTISAMPLE,
TEXTURE_2D_ARRAY, TEXTURE_2D_MULTISAMPLE_ARRAY, TEXTURE_CUBE_-
MAP or TEXTURE_CUBE_MAP_ARRAY. Using these formats in conjunction with
any other target will result in an INVALID_OPERATION error.
This patch can fix dEQP-GLES3.functional.negative_api.texture.teximage3d
failure.

Jira: https://01.org/jira/browse/AIA-9

Test: Pass dEQP-GLES3.functional.negative_api.texture.* and no
regression.

Signed-off-by: Xu,Randy <randy.xu@intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@tpalli   Shouldn't this be fixed in Mesa ?

@txu4 Can you send the patch for review to Mesa mailing list ?

**Comment by kalyankondapally** [comment]
hmm seems related https://code.google.com/p/android/issues/detail?id=200911 ?

**Comment by txu4** [comment]
It's glTexImage3D, not glFramebufferTexture2D. Not same issue as https://code.google.com/p/android/issues/detail?id=200911. 

I will submit the patch to mesa maillist after review by @tpalli

**Comment by tpalli** [comment]
this looks fine for me, be aware that this changes one test result in Mesa CI, piglit.spec.!opengl 1_2.tex3d-maxsize.g965m64 starts to crash (instead of previous status, which was fail). I don't consider this a blocker though, that test has been failing on that platform all along. Please send to the list!

**Comment by txu4** [comment]
Thanks @tpalli , I just submit the patch to mail list.

**Comment by kalyankondapally** [comment]
Can u add the link here, I dont see it in the mailing list ?

**Comment by kalyankondapally** [comment]
@txu4 Whats the status on this, should we close this ?

**Comment by txu4** [comment]
We can close it, as Mesa team  has filed a bug to Google as deqp case issue

**Pull request closed without merging**
